name: 📚Docs Report
description: Report an issue in ZSvirt documentation
title: "[Docs]: "
labels: ["kind/documentation"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What is wrong or missing?
      description: Describe the documentation issue.
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Documentation link
      placeholder: https://docs.zsvirt.io
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
      description: Tell us how the documentation could be improved.
    validations:
      required: false
